### ISSUE TITLE
Settings are saved when presets are selected

### ISSUE THREAD

**Issue by algernon-A** [ninjamods/Emergency-Lights-Manager-V2#1]
Settings are saved when custom settings are changed, but not when presets are.  Players who just select a preset (without touching the custom settings) won't have their selection saved.

This is because the presets dropdown event handler doesn't include a call to ExportSettings (unlike the custom settings dropdown events handlers).

The fix is simply to include an identical call to ExportSettings in the preset dropdown event handler (to be consistent with the other dropdowns, inserted between existing lines 354 and 355, immediately prior to the if (loaded) check).  I'd do a pull request, but I didn't think it was worth all the hassle for a one-line fix 😃

**Comment by ninjamods** [comment]
Thank you! Fixed and updated on the workshop

**Comment by algernon-A** [comment]
Glad to help!
